//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllowOrCharge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllowOrCharge">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndicatorCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}IndicatorCode"/>
 *         &lt;element name="IndicatorCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BasisCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}BasisCode" minOccurs="0"/>
 *         &lt;element name="BasisCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MethodOfHandlingCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}MethodOfHandlingCode"/>
 *         &lt;element name="MethodOfHandlingCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AllowanceOrChargeDescription">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}AllowOrChgDesc"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ValidityDates" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="BasisQuantityRange">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Quantity"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}BasisMonetaryRange"/>
 *         &lt;/choice>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}TypeOfAllowanceOrCharge"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Tax" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SeqNo" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllowOrCharge", propOrder = {
    "indicatorCoded",
    "indicatorCodedOther",
    "basisCoded",
    "basisCodedOther",
    "methodOfHandlingCoded",
    "methodOfHandlingCodedOther",
    "allowanceOrChargeDescription",
    "validityDates",
    "basisQuantityRange",
    "basisMonetaryRange",
    "typeOfAllowanceOrCharge",
    "tax"
})
public class AllowOrCharge {

    @XmlElement(name = "IndicatorCoded", required = true)
    protected IndicatorCode indicatorCoded;
    @XmlElement(name = "IndicatorCodedOther")
    protected String indicatorCodedOther;
    @XmlElement(name = "BasisCoded")
    protected BasisCode basisCoded;
    @XmlElement(name = "BasisCodedOther")
    protected String basisCodedOther;
    @XmlElement(name = "MethodOfHandlingCoded", required = true)
    protected MethodOfHandlingCode methodOfHandlingCoded;
    @XmlElement(name = "MethodOfHandlingCodedOther")
    protected String methodOfHandlingCodedOther;
    @XmlElement(name = "AllowanceOrChargeDescription", required = true)
    protected AllowOrCharge.AllowanceOrChargeDescription allowanceOrChargeDescription;
    @XmlElement(name = "ValidityDates")
    protected ValidityDates validityDates;
    @XmlElement(name = "BasisQuantityRange")
    protected AllowOrCharge.BasisQuantityRange basisQuantityRange;
    @XmlElement(name = "BasisMonetaryRange")
    protected BasisMonetaryRange basisMonetaryRange;
    @XmlElement(name = "TypeOfAllowanceOrCharge", required = true)
    protected TypeOfAllowanceOrCharge typeOfAllowanceOrCharge;
    @XmlElement(name = "Tax")
    protected List<Tax> tax;
    @XmlAttribute(name = "SeqNo")
    protected Integer seqNo;

    /**
     * Gets the value of the indicatorCoded property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorCode }
     *     
     */
    public IndicatorCode getIndicatorCoded() {
        return indicatorCoded;
    }

    /**
     * Sets the value of the indicatorCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorCode }
     *     
     */
    public void setIndicatorCoded(IndicatorCode value) {
        this.indicatorCoded = value;
    }

    /**
     * Gets the value of the indicatorCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorCodedOther() {
        return indicatorCodedOther;
    }

    /**
     * Sets the value of the indicatorCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorCodedOther(String value) {
        this.indicatorCodedOther = value;
    }

    /**
     * Gets the value of the basisCoded property.
     * 
     * @return
     *     possible object is
     *     {@link BasisCode }
     *     
     */
    public BasisCode getBasisCoded() {
        return basisCoded;
    }

    /**
     * Sets the value of the basisCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasisCode }
     *     
     */
    public void setBasisCoded(BasisCode value) {
        this.basisCoded = value;
    }

    /**
     * Gets the value of the basisCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasisCodedOther() {
        return basisCodedOther;
    }

    /**
     * Sets the value of the basisCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasisCodedOther(String value) {
        this.basisCodedOther = value;
    }

    /**
     * Gets the value of the methodOfHandlingCoded property.
     * 
     * @return
     *     possible object is
     *     {@link MethodOfHandlingCode }
     *     
     */
    public MethodOfHandlingCode getMethodOfHandlingCoded() {
        return methodOfHandlingCoded;
    }

    /**
     * Sets the value of the methodOfHandlingCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodOfHandlingCode }
     *     
     */
    public void setMethodOfHandlingCoded(MethodOfHandlingCode value) {
        this.methodOfHandlingCoded = value;
    }

    /**
     * Gets the value of the methodOfHandlingCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodOfHandlingCodedOther() {
        return methodOfHandlingCodedOther;
    }

    /**
     * Sets the value of the methodOfHandlingCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodOfHandlingCodedOther(String value) {
        this.methodOfHandlingCodedOther = value;
    }

    /**
     * Gets the value of the allowanceOrChargeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link AllowOrCharge.AllowanceOrChargeDescription }
     *     
     */
    public AllowOrCharge.AllowanceOrChargeDescription getAllowanceOrChargeDescription() {
        return allowanceOrChargeDescription;
    }

    /**
     * Sets the value of the allowanceOrChargeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowOrCharge.AllowanceOrChargeDescription }
     *     
     */
    public void setAllowanceOrChargeDescription(AllowOrCharge.AllowanceOrChargeDescription value) {
        this.allowanceOrChargeDescription = value;
    }

    /**
     * Gets the value of the validityDates property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityDates }
     *     
     */
    public ValidityDates getValidityDates() {
        return validityDates;
    }

    /**
     * Sets the value of the validityDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityDates }
     *     
     */
    public void setValidityDates(ValidityDates value) {
        this.validityDates = value;
    }

    /**
     * Gets the value of the basisQuantityRange property.
     * 
     * @return
     *     possible object is
     *     {@link AllowOrCharge.BasisQuantityRange }
     *     
     */
    public AllowOrCharge.BasisQuantityRange getBasisQuantityRange() {
        return basisQuantityRange;
    }

    /**
     * Sets the value of the basisQuantityRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowOrCharge.BasisQuantityRange }
     *     
     */
    public void setBasisQuantityRange(AllowOrCharge.BasisQuantityRange value) {
        this.basisQuantityRange = value;
    }

    /**
     * Gets the value of the basisMonetaryRange property.
     * 
     * @return
     *     possible object is
     *     {@link BasisMonetaryRange }
     *     
     */
    public BasisMonetaryRange getBasisMonetaryRange() {
        return basisMonetaryRange;
    }

    /**
     * Sets the value of the basisMonetaryRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasisMonetaryRange }
     *     
     */
    public void setBasisMonetaryRange(BasisMonetaryRange value) {
        this.basisMonetaryRange = value;
    }

    /**
     * Gets the value of the typeOfAllowanceOrCharge property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfAllowanceOrCharge }
     *     
     */
    public TypeOfAllowanceOrCharge getTypeOfAllowanceOrCharge() {
        return typeOfAllowanceOrCharge;
    }

    /**
     * Sets the value of the typeOfAllowanceOrCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfAllowanceOrCharge }
     *     
     */
    public void setTypeOfAllowanceOrCharge(TypeOfAllowanceOrCharge value) {
        this.typeOfAllowanceOrCharge = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tax }
     * 
     * 
     */
    public List<Tax> getTax() {
        if (tax == null) {
            tax = new ArrayList<Tax>();
        }
        return this.tax;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSeqNo() {
        if (seqNo == null) {
            return  1;
        } else {
            return seqNo;
        }
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqNo(Integer value) {
        this.seqNo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}AllowOrChgDesc"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowOrChgDesc"
    })
    public static class AllowanceOrChargeDescription {

        @XmlElement(name = "AllowOrChgDesc", required = true)
        protected AllowOrChgDesc allowOrChgDesc;

        /**
         * Gets the value of the allowOrChgDesc property.
         * 
         * @return
         *     possible object is
         *     {@link AllowOrChgDesc }
         *     
         */
        public AllowOrChgDesc getAllowOrChgDesc() {
            return allowOrChgDesc;
        }

        /**
         * Sets the value of the allowOrChgDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link AllowOrChgDesc }
         *     
         */
        public void setAllowOrChgDesc(AllowOrChgDesc value) {
            this.allowOrChgDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Quantity"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quantity"
    })
    public static class BasisQuantityRange {

        @XmlElement(name = "Quantity", required = true)
        protected Quantity quantity;

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setQuantity(Quantity value) {
            this.quantity = value;
        }

    }

}
