//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CargoClassification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CargoClassification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NatureOfGoods" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Identifier"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OperationalTypeCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}OperationalTypeCode" minOccurs="0"/>
 *         &lt;element name="OperationalTypeCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TypeOfCargo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CargoClassification", propOrder = {
    "natureOfGoods",
    "operationalTypeCoded",
    "operationalTypeCodedOther",
    "typeOfCargo"
})
public class CargoClassification {

    @XmlElement(name = "NatureOfGoods")
    protected CargoClassification.NatureOfGoods natureOfGoods;
    @XmlElement(name = "OperationalTypeCoded")
    protected OperationalTypeCode operationalTypeCoded;
    @XmlElement(name = "OperationalTypeCodedOther")
    protected String operationalTypeCodedOther;
    @XmlElement(name = "TypeOfCargo")
    protected String typeOfCargo;

    /**
     * Gets the value of the natureOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link CargoClassification.NatureOfGoods }
     *     
     */
    public CargoClassification.NatureOfGoods getNatureOfGoods() {
        return natureOfGoods;
    }

    /**
     * Sets the value of the natureOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link CargoClassification.NatureOfGoods }
     *     
     */
    public void setNatureOfGoods(CargoClassification.NatureOfGoods value) {
        this.natureOfGoods = value;
    }

    /**
     * Gets the value of the operationalTypeCoded property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalTypeCode }
     *     
     */
    public OperationalTypeCode getOperationalTypeCoded() {
        return operationalTypeCoded;
    }

    /**
     * Sets the value of the operationalTypeCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalTypeCode }
     *     
     */
    public void setOperationalTypeCoded(OperationalTypeCode value) {
        this.operationalTypeCoded = value;
    }

    /**
     * Gets the value of the operationalTypeCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalTypeCodedOther() {
        return operationalTypeCodedOther;
    }

    /**
     * Sets the value of the operationalTypeCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalTypeCodedOther(String value) {
        this.operationalTypeCodedOther = value;
    }

    /**
     * Gets the value of the typeOfCargo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfCargo() {
        return typeOfCargo;
    }

    /**
     * Sets the value of the typeOfCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfCargo(String value) {
        this.typeOfCargo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Identifier"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier"
    })
    public static class NatureOfGoods {

        @XmlElement(name = "Identifier", required = true)
        protected Identifier identifier;

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link Identifier }
         *     
         */
        public Identifier getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Identifier }
         *     
         */
        public void setIdentifier(Identifier value) {
            this.identifier = value;
        }

    }

}
