//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentStatusCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EquipmentStatusCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Continental"/>
 *     &lt;enumeration value="Export"/>
 *     &lt;enumeration value="Import"/>
 *     &lt;enumeration value="RemainOnBoard"/>
 *     &lt;enumeration value="Shifter"/>
 *     &lt;enumeration value="Transhipment"/>
 *     &lt;enumeration value="Shortlanded"/>
 *     &lt;enumeration value="Overlanded"/>
 *     &lt;enumeration value="Domestic"/>
 *     &lt;enumeration value="Positioning"/>
 *     &lt;enumeration value="Delivery"/>
 *     &lt;enumeration value="Redelivery"/>
 *     &lt;enumeration value="Repair"/>
 *     &lt;enumeration value="Reloader"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EquipmentStatusCode")
@XmlEnum
public enum EquipmentStatusCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Continental")
    CONTINENTAL("Continental"),
    @XmlEnumValue("Export")
    EXPORT("Export"),
    @XmlEnumValue("Import")
    IMPORT("Import"),
    @XmlEnumValue("RemainOnBoard")
    REMAIN_ON_BOARD("RemainOnBoard"),
    @XmlEnumValue("Shifter")
    SHIFTER("Shifter"),
    @XmlEnumValue("Transhipment")
    TRANSHIPMENT("Transhipment"),
    @XmlEnumValue("Shortlanded")
    SHORTLANDED("Shortlanded"),
    @XmlEnumValue("Overlanded")
    OVERLANDED("Overlanded"),
    @XmlEnumValue("Domestic")
    DOMESTIC("Domestic"),
    @XmlEnumValue("Positioning")
    POSITIONING("Positioning"),
    @XmlEnumValue("Delivery")
    DELIVERY("Delivery"),
    @XmlEnumValue("Redelivery")
    REDELIVERY("Redelivery"),
    @XmlEnumValue("Repair")
    REPAIR("Repair"),
    @XmlEnumValue("Reloader")
    RELOADER("Reloader");
    private final String value;

    EquipmentStatusCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EquipmentStatusCode fromValue(String v) {
        for (EquipmentStatusCode c: EquipmentStatusCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
