//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FIAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FIAccount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}AccountDetail" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}FinancialInstitution"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FIAccount", propOrder = {
    "accountDetail",
    "financialInstitution"
})
public class FIAccount {

    @XmlElement(name = "AccountDetail")
    protected AccountDetail accountDetail;
    @XmlElement(name = "FinancialInstitution", required = true)
    protected FinancialInstitution financialInstitution;

    /**
     * Gets the value of the accountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetail }
     *     
     */
    public AccountDetail getAccountDetail() {
        return accountDetail;
    }

    /**
     * Sets the value of the accountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetail }
     *     
     */
    public void setAccountDetail(AccountDetail value) {
        this.accountDetail = value;
    }

    /**
     * Gets the value of the financialInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstitution }
     *     
     */
    public FinancialInstitution getFinancialInstitution() {
        return financialInstitution;
    }

    /**
     * Sets the value of the financialInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstitution }
     *     
     */
    public void setFinancialInstitution(FinancialInstitution value) {
        this.financialInstitution = value;
    }

}
