//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineItemNum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineItemNum">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerLineItemNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SellerLineItemNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineItemNum", propOrder = {
    "buyerLineItemNum",
    "sellerLineItemNum"
})
public class LineItemNum {

    @XmlElement(name = "BuyerLineItemNum")
    protected int buyerLineItemNum;
    @XmlElement(name = "SellerLineItemNum")
    protected Integer sellerLineItemNum;

    /**
     * Gets the value of the buyerLineItemNum property.
     * 
     */
    public int getBuyerLineItemNum() {
        return buyerLineItemNum;
    }

    /**
     * Sets the value of the buyerLineItemNum property.
     * 
     */
    public void setBuyerLineItemNum(int value) {
        this.buyerLineItemNum = value;
    }

    /**
     * Gets the value of the sellerLineItemNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSellerLineItemNum() {
        return sellerLineItemNum;
    }

    /**
     * Sets the value of the sellerLineItemNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSellerLineItemNum(Integer value) {
        this.sellerLineItemNum = value;
    }

}
