//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderInvoiceMediumTypeCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderInvoiceMediumTypeCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Circuitswitching"/>
 *     &lt;enumeration value="SITA"/>
 *     &lt;enumeration value="ARINC"/>
 *     &lt;enumeration value="Courier"/>
 *     &lt;enumeration value="CableAddress"/>
 *     &lt;enumeration value="EDITransmission"/>
 *     &lt;enumeration value="ElectronicMail"/>
 *     &lt;enumeration value="Extension"/>
 *     &lt;enumeration value="FileTransferAccessMethod"/>
 *     &lt;enumeration value="TeleFax"/>
 *     &lt;enumeration value="GEISMailbox"/>
 *     &lt;enumeration value="IBMInformationExchange"/>
 *     &lt;enumeration value="InternalMail"/>
 *     &lt;enumeration value="Mail"/>
 *     &lt;enumeration value="PostBoxNo"/>
 *     &lt;enumeration value="PacketSwitching"/>
 *     &lt;enumeration value="SWIFT"/>
 *     &lt;enumeration value="Telephone"/>
 *     &lt;enumeration value="Telegraph"/>
 *     &lt;enumeration value="Telex"/>
 *     &lt;enumeration value="TeleMail"/>
 *     &lt;enumeration value="TeleText"/>
 *     &lt;enumeration value="TWX"/>
 *     &lt;enumeration value="X.400"/>
 *     &lt;enumeration value="NotRequired"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OrderInvoiceMediumTypeCode")
@XmlEnum
public enum OrderInvoiceMediumTypeCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Circuitswitching")
    CIRCUITSWITCHING("Circuitswitching"),
    SITA("SITA"),
    ARINC("ARINC"),
    @XmlEnumValue("Courier")
    COURIER("Courier"),
    @XmlEnumValue("CableAddress")
    CABLE_ADDRESS("CableAddress"),
    @XmlEnumValue("EDITransmission")
    EDI_TRANSMISSION("EDITransmission"),
    @XmlEnumValue("ElectronicMail")
    ELECTRONIC_MAIL("ElectronicMail"),
    @XmlEnumValue("Extension")
    EXTENSION("Extension"),
    @XmlEnumValue("FileTransferAccessMethod")
    FILE_TRANSFER_ACCESS_METHOD("FileTransferAccessMethod"),
    @XmlEnumValue("TeleFax")
    TELE_FAX("TeleFax"),
    @XmlEnumValue("GEISMailbox")
    GEIS_MAILBOX("GEISMailbox"),
    @XmlEnumValue("IBMInformationExchange")
    IBM_INFORMATION_EXCHANGE("IBMInformationExchange"),
    @XmlEnumValue("InternalMail")
    INTERNAL_MAIL("InternalMail"),
    @XmlEnumValue("Mail")
    MAIL("Mail"),
    @XmlEnumValue("PostBoxNo")
    POST_BOX_NO("PostBoxNo"),
    @XmlEnumValue("PacketSwitching")
    PACKET_SWITCHING("PacketSwitching"),
    SWIFT("SWIFT"),
    @XmlEnumValue("Telephone")
    TELEPHONE("Telephone"),
    @XmlEnumValue("Telegraph")
    TELEGRAPH("Telegraph"),
    @XmlEnumValue("Telex")
    TELEX("Telex"),
    @XmlEnumValue("TeleMail")
    TELE_MAIL("TeleMail"),
    @XmlEnumValue("TeleText")
    TELE_TEXT("TeleText"),
    TWX("TWX"),
    @XmlEnumValue("X.400")
    X_400("X.400"),
    @XmlEnumValue("NotRequired")
    NOT_REQUIRED("NotRequired");
    private final String value;

    OrderInvoiceMediumTypeCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderInvoiceMediumTypeCode fromValue(String v) {
        for (OrderInvoiceMediumTypeCode c: OrderInvoiceMediumTypeCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
