//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderParty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderParty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerParty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BuyerTaxInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartyTaxInformation"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SellerParty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SellerTaxInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartyTaxInformation"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipToParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BillToParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RemitToParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipFromParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WarehouseParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SoldToParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ManufacturingToParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaterialIssuer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfPartyCoded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderParty", propOrder = {
    "buyerParty",
    "buyerTaxInformation",
    "sellerParty",
    "sellerTaxInformation",
    "shipToParty",
    "billToParty",
    "remitToParty",
    "shipFromParty",
    "warehouseParty",
    "soldToParty",
    "manufacturingToParty",
    "materialIssuer",
    "listOfPartyCoded"
})
public class OrderParty {

    @XmlElement(name = "BuyerParty", required = true)
    protected OrderParty.BuyerParty buyerParty;
    @XmlElement(name = "BuyerTaxInformation")
    protected OrderParty.BuyerTaxInformation buyerTaxInformation;
    @XmlElement(name = "SellerParty", required = true)
    protected OrderParty.SellerParty sellerParty;
    @XmlElement(name = "SellerTaxInformation")
    protected OrderParty.SellerTaxInformation sellerTaxInformation;
    @XmlElement(name = "ShipToParty")
    protected OrderParty.ShipToParty shipToParty;
    @XmlElement(name = "BillToParty")
    protected OrderParty.BillToParty billToParty;
    @XmlElement(name = "RemitToParty")
    protected OrderParty.RemitToParty remitToParty;
    @XmlElement(name = "ShipFromParty")
    protected OrderParty.ShipFromParty shipFromParty;
    @XmlElement(name = "WarehouseParty")
    protected OrderParty.WarehouseParty warehouseParty;
    @XmlElement(name = "SoldToParty")
    protected OrderParty.SoldToParty soldToParty;
    @XmlElement(name = "ManufacturingToParty")
    protected OrderParty.ManufacturingToParty manufacturingToParty;
    @XmlElement(name = "MaterialIssuer")
    protected OrderParty.MaterialIssuer materialIssuer;
    @XmlElement(name = "ListOfPartyCoded")
    protected ListOfPartyCoded listOfPartyCoded;

    /**
     * Gets the value of the buyerParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.BuyerParty }
     *     
     */
    public OrderParty.BuyerParty getBuyerParty() {
        return buyerParty;
    }

    /**
     * Sets the value of the buyerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.BuyerParty }
     *     
     */
    public void setBuyerParty(OrderParty.BuyerParty value) {
        this.buyerParty = value;
    }

    /**
     * Gets the value of the buyerTaxInformation property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.BuyerTaxInformation }
     *     
     */
    public OrderParty.BuyerTaxInformation getBuyerTaxInformation() {
        return buyerTaxInformation;
    }

    /**
     * Sets the value of the buyerTaxInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.BuyerTaxInformation }
     *     
     */
    public void setBuyerTaxInformation(OrderParty.BuyerTaxInformation value) {
        this.buyerTaxInformation = value;
    }

    /**
     * Gets the value of the sellerParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.SellerParty }
     *     
     */
    public OrderParty.SellerParty getSellerParty() {
        return sellerParty;
    }

    /**
     * Sets the value of the sellerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.SellerParty }
     *     
     */
    public void setSellerParty(OrderParty.SellerParty value) {
        this.sellerParty = value;
    }

    /**
     * Gets the value of the sellerTaxInformation property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.SellerTaxInformation }
     *     
     */
    public OrderParty.SellerTaxInformation getSellerTaxInformation() {
        return sellerTaxInformation;
    }

    /**
     * Sets the value of the sellerTaxInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.SellerTaxInformation }
     *     
     */
    public void setSellerTaxInformation(OrderParty.SellerTaxInformation value) {
        this.sellerTaxInformation = value;
    }

    /**
     * Gets the value of the shipToParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.ShipToParty }
     *     
     */
    public OrderParty.ShipToParty getShipToParty() {
        return shipToParty;
    }

    /**
     * Sets the value of the shipToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.ShipToParty }
     *     
     */
    public void setShipToParty(OrderParty.ShipToParty value) {
        this.shipToParty = value;
    }

    /**
     * Gets the value of the billToParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.BillToParty }
     *     
     */
    public OrderParty.BillToParty getBillToParty() {
        return billToParty;
    }

    /**
     * Sets the value of the billToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.BillToParty }
     *     
     */
    public void setBillToParty(OrderParty.BillToParty value) {
        this.billToParty = value;
    }

    /**
     * Gets the value of the remitToParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.RemitToParty }
     *     
     */
    public OrderParty.RemitToParty getRemitToParty() {
        return remitToParty;
    }

    /**
     * Sets the value of the remitToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.RemitToParty }
     *     
     */
    public void setRemitToParty(OrderParty.RemitToParty value) {
        this.remitToParty = value;
    }

    /**
     * Gets the value of the shipFromParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.ShipFromParty }
     *     
     */
    public OrderParty.ShipFromParty getShipFromParty() {
        return shipFromParty;
    }

    /**
     * Sets the value of the shipFromParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.ShipFromParty }
     *     
     */
    public void setShipFromParty(OrderParty.ShipFromParty value) {
        this.shipFromParty = value;
    }

    /**
     * Gets the value of the warehouseParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.WarehouseParty }
     *     
     */
    public OrderParty.WarehouseParty getWarehouseParty() {
        return warehouseParty;
    }

    /**
     * Sets the value of the warehouseParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.WarehouseParty }
     *     
     */
    public void setWarehouseParty(OrderParty.WarehouseParty value) {
        this.warehouseParty = value;
    }

    /**
     * Gets the value of the soldToParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.SoldToParty }
     *     
     */
    public OrderParty.SoldToParty getSoldToParty() {
        return soldToParty;
    }

    /**
     * Sets the value of the soldToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.SoldToParty }
     *     
     */
    public void setSoldToParty(OrderParty.SoldToParty value) {
        this.soldToParty = value;
    }

    /**
     * Gets the value of the manufacturingToParty property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.ManufacturingToParty }
     *     
     */
    public OrderParty.ManufacturingToParty getManufacturingToParty() {
        return manufacturingToParty;
    }

    /**
     * Sets the value of the manufacturingToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.ManufacturingToParty }
     *     
     */
    public void setManufacturingToParty(OrderParty.ManufacturingToParty value) {
        this.manufacturingToParty = value;
    }

    /**
     * Gets the value of the materialIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link OrderParty.MaterialIssuer }
     *     
     */
    public OrderParty.MaterialIssuer getMaterialIssuer() {
        return materialIssuer;
    }

    /**
     * Sets the value of the materialIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderParty.MaterialIssuer }
     *     
     */
    public void setMaterialIssuer(OrderParty.MaterialIssuer value) {
        this.materialIssuer = value;
    }

    /**
     * Gets the value of the listOfPartyCoded property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPartyCoded }
     *     
     */
    public ListOfPartyCoded getListOfPartyCoded() {
        return listOfPartyCoded;
    }

    /**
     * Sets the value of the listOfPartyCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPartyCoded }
     *     
     */
    public void setListOfPartyCoded(ListOfPartyCoded value) {
        this.listOfPartyCoded = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class BillToParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class BuyerParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartyTaxInformation"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyTaxInformation"
    })
    public static class BuyerTaxInformation {

        @XmlElement(name = "PartyTaxInformation", required = true)
        protected PartyTaxInformation partyTaxInformation;

        /**
         * Gets the value of the partyTaxInformation property.
         * 
         * @return
         *     possible object is
         *     {@link PartyTaxInformation }
         *     
         */
        public PartyTaxInformation getPartyTaxInformation() {
            return partyTaxInformation;
        }

        /**
         * Sets the value of the partyTaxInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartyTaxInformation }
         *     
         */
        public void setPartyTaxInformation(PartyTaxInformation value) {
            this.partyTaxInformation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class ManufacturingToParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class MaterialIssuer {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class RemitToParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class SellerParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartyTaxInformation"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyTaxInformation"
    })
    public static class SellerTaxInformation {

        @XmlElement(name = "PartyTaxInformation", required = true)
        protected PartyTaxInformation partyTaxInformation;

        /**
         * Gets the value of the partyTaxInformation property.
         * 
         * @return
         *     possible object is
         *     {@link PartyTaxInformation }
         *     
         */
        public PartyTaxInformation getPartyTaxInformation() {
            return partyTaxInformation;
        }

        /**
         * Sets the value of the partyTaxInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartyTaxInformation }
         *     
         */
        public void setPartyTaxInformation(PartyTaxInformation value) {
            this.partyTaxInformation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class ShipFromParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class ShipToParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class SoldToParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Party"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "party"
    })
    public static class WarehouseParty {

        @XmlElement(name = "Party", required = true)
        protected Party party;

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

    }

}
