//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PackageType"/>
 *         &lt;element name="NumberOfPackages" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfPackage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageDetail", propOrder = {
    "packageType",
    "numberOfPackages",
    "listOfPackage"
})
public class PackageDetail {

    @XmlElement(name = "PackageType", required = true)
    protected PackageType packageType;
    @XmlElement(name = "NumberOfPackages")
    protected int numberOfPackages;
    @XmlElement(name = "ListOfPackage")
    protected ListOfPackage listOfPackage;

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link PackageType }
     *     
     */
    public PackageType getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageType }
     *     
     */
    public void setPackageType(PackageType value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the numberOfPackages property.
     * 
     */
    public int getNumberOfPackages() {
        return numberOfPackages;
    }

    /**
     * Sets the value of the numberOfPackages property.
     * 
     */
    public void setNumberOfPackages(int value) {
        this.numberOfPackages = value;
    }

    /**
     * Gets the value of the listOfPackage property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPackage }
     *     
     */
    public ListOfPackage getListOfPackage() {
        return listOfPackage;
    }

    /**
     * Sets the value of the listOfPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPackage }
     *     
     */
    public void setListOfPackage(ListOfPackage value) {
        this.listOfPackage = value;
    }

}
