//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Package complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Package">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ListOfItemReference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfOrderReferences"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfPackageMark" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfPackageCharacteristic" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfDimension" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfPackageDescription" minOccurs="0"/>
 *         &lt;element name="TransportReference" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}SpecialHandling" minOccurs="0"/>
 *         &lt;element name="HazardousPackaging" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Hazardous"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}AssociatedDocuments" minOccurs="0"/>
 *         &lt;element name="ShippingInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ReturnableContainerInfo" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PackageDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Package", propOrder = {
    "packageID",
    "listOfItemReference",
    "listOfPackageMark",
    "listOfPackageCharacteristic",
    "listOfDimension",
    "listOfPackageDescription",
    "transportReference",
    "specialHandling",
    "hazardousPackaging",
    "associatedDocuments",
    "shippingInstructions",
    "returnableContainerInfo",
    "packageDetail"
})
public class Package {

    @XmlElement(name = "PackageID")
    protected int packageID;
    @XmlElement(name = "ListOfItemReference")
    protected Package.ListOfItemReference listOfItemReference;
    @XmlElement(name = "ListOfPackageMark")
    protected ListOfPackageMark listOfPackageMark;
    @XmlElement(name = "ListOfPackageCharacteristic")
    protected ListOfPackageCharacteristic listOfPackageCharacteristic;
    @XmlElement(name = "ListOfDimension")
    protected ListOfDimension listOfDimension;
    @XmlElement(name = "ListOfPackageDescription")
    protected ListOfPackageDescription listOfPackageDescription;
    @XmlElement(name = "TransportReference")
    protected Integer transportReference;
    @XmlElement(name = "SpecialHandling")
    protected SpecialHandling specialHandling;
    @XmlElement(name = "HazardousPackaging")
    protected Package.HazardousPackaging hazardousPackaging;
    @XmlElement(name = "AssociatedDocuments")
    protected AssociatedDocuments associatedDocuments;
    @XmlElement(name = "ShippingInstructions")
    protected String shippingInstructions;
    @XmlElement(name = "ReturnableContainerInfo")
    protected ReturnableContainerInfo returnableContainerInfo;
    @XmlElement(name = "PackageDetail")
    protected List<PackageDetail> packageDetail;

    /**
     * Gets the value of the packageID property.
     * 
     */
    public int getPackageID() {
        return packageID;
    }

    /**
     * Sets the value of the packageID property.
     * 
     */
    public void setPackageID(int value) {
        this.packageID = value;
    }

    /**
     * Gets the value of the listOfItemReference property.
     * 
     * @return
     *     possible object is
     *     {@link Package.ListOfItemReference }
     *     
     */
    public Package.ListOfItemReference getListOfItemReference() {
        return listOfItemReference;
    }

    /**
     * Sets the value of the listOfItemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Package.ListOfItemReference }
     *     
     */
    public void setListOfItemReference(Package.ListOfItemReference value) {
        this.listOfItemReference = value;
    }

    /**
     * Gets the value of the listOfPackageMark property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPackageMark }
     *     
     */
    public ListOfPackageMark getListOfPackageMark() {
        return listOfPackageMark;
    }

    /**
     * Sets the value of the listOfPackageMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPackageMark }
     *     
     */
    public void setListOfPackageMark(ListOfPackageMark value) {
        this.listOfPackageMark = value;
    }

    /**
     * Gets the value of the listOfPackageCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPackageCharacteristic }
     *     
     */
    public ListOfPackageCharacteristic getListOfPackageCharacteristic() {
        return listOfPackageCharacteristic;
    }

    /**
     * Sets the value of the listOfPackageCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPackageCharacteristic }
     *     
     */
    public void setListOfPackageCharacteristic(ListOfPackageCharacteristic value) {
        this.listOfPackageCharacteristic = value;
    }

    /**
     * Gets the value of the listOfDimension property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfDimension }
     *     
     */
    public ListOfDimension getListOfDimension() {
        return listOfDimension;
    }

    /**
     * Sets the value of the listOfDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfDimension }
     *     
     */
    public void setListOfDimension(ListOfDimension value) {
        this.listOfDimension = value;
    }

    /**
     * Gets the value of the listOfPackageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPackageDescription }
     *     
     */
    public ListOfPackageDescription getListOfPackageDescription() {
        return listOfPackageDescription;
    }

    /**
     * Sets the value of the listOfPackageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPackageDescription }
     *     
     */
    public void setListOfPackageDescription(ListOfPackageDescription value) {
        this.listOfPackageDescription = value;
    }

    /**
     * Gets the value of the transportReference property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransportReference() {
        return transportReference;
    }

    /**
     * Sets the value of the transportReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransportReference(Integer value) {
        this.transportReference = value;
    }

    /**
     * Gets the value of the specialHandling property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialHandling }
     *     
     */
    public SpecialHandling getSpecialHandling() {
        return specialHandling;
    }

    /**
     * Sets the value of the specialHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialHandling }
     *     
     */
    public void setSpecialHandling(SpecialHandling value) {
        this.specialHandling = value;
    }

    /**
     * Gets the value of the hazardousPackaging property.
     * 
     * @return
     *     possible object is
     *     {@link Package.HazardousPackaging }
     *     
     */
    public Package.HazardousPackaging getHazardousPackaging() {
        return hazardousPackaging;
    }

    /**
     * Sets the value of the hazardousPackaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Package.HazardousPackaging }
     *     
     */
    public void setHazardousPackaging(Package.HazardousPackaging value) {
        this.hazardousPackaging = value;
    }

    /**
     * Gets the value of the associatedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedDocuments }
     *     
     */
    public AssociatedDocuments getAssociatedDocuments() {
        return associatedDocuments;
    }

    /**
     * Sets the value of the associatedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedDocuments }
     *     
     */
    public void setAssociatedDocuments(AssociatedDocuments value) {
        this.associatedDocuments = value;
    }

    /**
     * Gets the value of the shippingInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingInstructions() {
        return shippingInstructions;
    }

    /**
     * Sets the value of the shippingInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingInstructions(String value) {
        this.shippingInstructions = value;
    }

    /**
     * Gets the value of the returnableContainerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnableContainerInfo }
     *     
     */
    public ReturnableContainerInfo getReturnableContainerInfo() {
        return returnableContainerInfo;
    }

    /**
     * Sets the value of the returnableContainerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnableContainerInfo }
     *     
     */
    public void setReturnableContainerInfo(ReturnableContainerInfo value) {
        this.returnableContainerInfo = value;
    }

    /**
     * Gets the value of the packageDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackageDetail }
     * 
     * 
     */
    public List<PackageDetail> getPackageDetail() {
        if (packageDetail == null) {
            packageDetail = new ArrayList<PackageDetail>();
        }
        return this.packageDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Hazardous"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hazardous"
    })
    public static class HazardousPackaging {

        @XmlElement(name = "Hazardous", required = true)
        protected Hazardous hazardous;

        /**
         * Gets the value of the hazardous property.
         * 
         * @return
         *     possible object is
         *     {@link Hazardous }
         *     
         */
        public Hazardous getHazardous() {
            return hazardous;
        }

        /**
         * Sets the value of the hazardous property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hazardous }
         *     
         */
        public void setHazardous(Hazardous value) {
            this.hazardous = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfOrderReferences"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listOfOrderReferences"
    })
    public static class ListOfItemReference {

        @XmlElement(name = "ListOfOrderReferences", required = true)
        protected ListOfOrderReferences listOfOrderReferences;

        /**
         * Gets the value of the listOfOrderReferences property.
         * 
         * @return
         *     possible object is
         *     {@link ListOfOrderReferences }
         *     
         */
        public ListOfOrderReferences getListOfOrderReferences() {
            return listOfOrderReferences;
        }

        /**
         * Sets the value of the listOfOrderReferences property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListOfOrderReferences }
         *     
         */
        public void setListOfOrderReferences(ListOfOrderReferences value) {
            this.listOfOrderReferences = value;
        }

    }

}
