//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageCharacteristic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageCharacteristic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageCharacteristicCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PackageCharacteristicCode"/>
 *         &lt;element name="PackageCharacteristicCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PackageCharacteristicDescription">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Identifier"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageCharacteristic", propOrder = {
    "packageCharacteristicCoded",
    "packageCharacteristicCodedOther",
    "packageCharacteristicDescription"
})
public class PackageCharacteristic {

    @XmlElement(name = "PackageCharacteristicCoded", required = true)
    protected PackageCharacteristicCode packageCharacteristicCoded;
    @XmlElement(name = "PackageCharacteristicCodedOther")
    protected String packageCharacteristicCodedOther;
    @XmlElement(name = "PackageCharacteristicDescription", required = true)
    protected PackageCharacteristic.PackageCharacteristicDescription packageCharacteristicDescription;

    /**
     * Gets the value of the packageCharacteristicCoded property.
     * 
     * @return
     *     possible object is
     *     {@link PackageCharacteristicCode }
     *     
     */
    public PackageCharacteristicCode getPackageCharacteristicCoded() {
        return packageCharacteristicCoded;
    }

    /**
     * Sets the value of the packageCharacteristicCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageCharacteristicCode }
     *     
     */
    public void setPackageCharacteristicCoded(PackageCharacteristicCode value) {
        this.packageCharacteristicCoded = value;
    }

    /**
     * Gets the value of the packageCharacteristicCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageCharacteristicCodedOther() {
        return packageCharacteristicCodedOther;
    }

    /**
     * Sets the value of the packageCharacteristicCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageCharacteristicCodedOther(String value) {
        this.packageCharacteristicCodedOther = value;
    }

    /**
     * Gets the value of the packageCharacteristicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link PackageCharacteristic.PackageCharacteristicDescription }
     *     
     */
    public PackageCharacteristic.PackageCharacteristicDescription getPackageCharacteristicDescription() {
        return packageCharacteristicDescription;
    }

    /**
     * Sets the value of the packageCharacteristicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageCharacteristic.PackageCharacteristicDescription }
     *     
     */
    public void setPackageCharacteristicDescription(PackageCharacteristic.PackageCharacteristicDescription value) {
        this.packageCharacteristicDescription = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Identifier"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier"
    })
    public static class PackageCharacteristicDescription {

        @XmlElement(name = "Identifier", required = true)
        protected Identifier identifier;

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link Identifier }
         *     
         */
        public Identifier getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Identifier }
         *     
         */
        public void setIdentifier(Identifier value) {
            this.identifier = value;
        }

    }

}
