//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageMarkCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PackageMarkCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="BuyersInstructions"/>
 *     &lt;enumeration value="Carrier-AssignedPackageIdNumber"/>
 *     &lt;enumeration value="CarriersInstructions"/>
 *     &lt;enumeration value="DoNotMarkSuppliersCompanyName"/>
 *     &lt;enumeration value="EntireShipment"/>
 *     &lt;enumeration value="IndustryInstructions"/>
 *     &lt;enumeration value="LegalRequirements"/>
 *     &lt;enumeration value="LineItemOnly"/>
 *     &lt;enumeration value="MarkAdditionallyCustomersArticleDescription"/>
 *     &lt;enumeration value="MarkArticleNumberCustomer"/>
 *     &lt;enumeration value="MarkBatchNumber"/>
 *     &lt;enumeration value="MarkCaseNumber"/>
 *     &lt;enumeration value="MarkCustomersCompanyName"/>
 *     &lt;enumeration value="MarkCustomersReferences"/>
 *     &lt;enumeration value="MarkDateOfProduction"/>
 *     &lt;enumeration value="MarkExclusivelyCustomersArticleDescription"/>
 *     &lt;enumeration value="MarkExpiryDate"/>
 *     &lt;enumeration value="MarkFreeText"/>
 *     &lt;enumeration value="MarkGrossWeight"/>
 *     &lt;enumeration value="MarkNetWeight"/>
 *     &lt;enumeration value="MarkPackagesDimensions"/>
 *     &lt;enumeration value="MarkRunningNumberOfPackages"/>
 *     &lt;enumeration value="MarkSerialShippingContainerCode"/>
 *     &lt;enumeration value="MarkSupplierNumber"/>
 *     &lt;enumeration value="MarkTareWeight"/>
 *     &lt;enumeration value="MasterCartonNumber"/>
 *     &lt;enumeration value="OriginatorAssigned"/>
 *     &lt;enumeration value="PalletConfigurationNumber"/>
 *     &lt;enumeration value="PalletNumber"/>
 *     &lt;enumeration value="PreMarkedByBuyer"/>
 *     &lt;enumeration value="ReceiverAssignedDropZone"/>
 *     &lt;enumeration value="Self-IdentifyingContainerViaRadioFrequencyIdDevice"/>
 *     &lt;enumeration value="SellersInstructions"/>
 *     &lt;enumeration value="ShipperAssigned"/>
 *     &lt;enumeration value="Shipper-AssignedCaseNumber"/>
 *     &lt;enumeration value="ShipperAssignedRollNumber"/>
 *     &lt;enumeration value="ShipperAssignedSkidNumber"/>
 *     &lt;enumeration value="SSCC-18"/>
 *     &lt;enumeration value="SSCC-18AndApplicationIdentifier"/>
 *     &lt;enumeration value="UPCShippingContainerCode"/>
 *     &lt;enumeration value="UCCOrEAN128ApplicationIdentifierAndData"/>
 *     &lt;enumeration value="UniformCodeCouncilFormat"/>
 *     &lt;enumeration value="UPCConsumerPackageCode-1-5-5-1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PackageMarkCode")
@XmlEnum
public enum PackageMarkCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("BuyersInstructions")
    BUYERS_INSTRUCTIONS("BuyersInstructions"),
    @XmlEnumValue("Carrier-AssignedPackageIdNumber")
    CARRIER_ASSIGNED_PACKAGE_ID_NUMBER("Carrier-AssignedPackageIdNumber"),
    @XmlEnumValue("CarriersInstructions")
    CARRIERS_INSTRUCTIONS("CarriersInstructions"),
    @XmlEnumValue("DoNotMarkSuppliersCompanyName")
    DO_NOT_MARK_SUPPLIERS_COMPANY_NAME("DoNotMarkSuppliersCompanyName"),
    @XmlEnumValue("EntireShipment")
    ENTIRE_SHIPMENT("EntireShipment"),
    @XmlEnumValue("IndustryInstructions")
    INDUSTRY_INSTRUCTIONS("IndustryInstructions"),
    @XmlEnumValue("LegalRequirements")
    LEGAL_REQUIREMENTS("LegalRequirements"),
    @XmlEnumValue("LineItemOnly")
    LINE_ITEM_ONLY("LineItemOnly"),
    @XmlEnumValue("MarkAdditionallyCustomersArticleDescription")
    MARK_ADDITIONALLY_CUSTOMERS_ARTICLE_DESCRIPTION("MarkAdditionallyCustomersArticleDescription"),
    @XmlEnumValue("MarkArticleNumberCustomer")
    MARK_ARTICLE_NUMBER_CUSTOMER("MarkArticleNumberCustomer"),
    @XmlEnumValue("MarkBatchNumber")
    MARK_BATCH_NUMBER("MarkBatchNumber"),
    @XmlEnumValue("MarkCaseNumber")
    MARK_CASE_NUMBER("MarkCaseNumber"),
    @XmlEnumValue("MarkCustomersCompanyName")
    MARK_CUSTOMERS_COMPANY_NAME("MarkCustomersCompanyName"),
    @XmlEnumValue("MarkCustomersReferences")
    MARK_CUSTOMERS_REFERENCES("MarkCustomersReferences"),
    @XmlEnumValue("MarkDateOfProduction")
    MARK_DATE_OF_PRODUCTION("MarkDateOfProduction"),
    @XmlEnumValue("MarkExclusivelyCustomersArticleDescription")
    MARK_EXCLUSIVELY_CUSTOMERS_ARTICLE_DESCRIPTION("MarkExclusivelyCustomersArticleDescription"),
    @XmlEnumValue("MarkExpiryDate")
    MARK_EXPIRY_DATE("MarkExpiryDate"),
    @XmlEnumValue("MarkFreeText")
    MARK_FREE_TEXT("MarkFreeText"),
    @XmlEnumValue("MarkGrossWeight")
    MARK_GROSS_WEIGHT("MarkGrossWeight"),
    @XmlEnumValue("MarkNetWeight")
    MARK_NET_WEIGHT("MarkNetWeight"),
    @XmlEnumValue("MarkPackagesDimensions")
    MARK_PACKAGES_DIMENSIONS("MarkPackagesDimensions"),
    @XmlEnumValue("MarkRunningNumberOfPackages")
    MARK_RUNNING_NUMBER_OF_PACKAGES("MarkRunningNumberOfPackages"),
    @XmlEnumValue("MarkSerialShippingContainerCode")
    MARK_SERIAL_SHIPPING_CONTAINER_CODE("MarkSerialShippingContainerCode"),
    @XmlEnumValue("MarkSupplierNumber")
    MARK_SUPPLIER_NUMBER("MarkSupplierNumber"),
    @XmlEnumValue("MarkTareWeight")
    MARK_TARE_WEIGHT("MarkTareWeight"),
    @XmlEnumValue("MasterCartonNumber")
    MASTER_CARTON_NUMBER("MasterCartonNumber"),
    @XmlEnumValue("OriginatorAssigned")
    ORIGINATOR_ASSIGNED("OriginatorAssigned"),
    @XmlEnumValue("PalletConfigurationNumber")
    PALLET_CONFIGURATION_NUMBER("PalletConfigurationNumber"),
    @XmlEnumValue("PalletNumber")
    PALLET_NUMBER("PalletNumber"),
    @XmlEnumValue("PreMarkedByBuyer")
    PRE_MARKED_BY_BUYER("PreMarkedByBuyer"),
    @XmlEnumValue("ReceiverAssignedDropZone")
    RECEIVER_ASSIGNED_DROP_ZONE("ReceiverAssignedDropZone"),
    @XmlEnumValue("Self-IdentifyingContainerViaRadioFrequencyIdDevice")
    SELF_IDENTIFYING_CONTAINER_VIA_RADIO_FREQUENCY_ID_DEVICE("Self-IdentifyingContainerViaRadioFrequencyIdDevice"),
    @XmlEnumValue("SellersInstructions")
    SELLERS_INSTRUCTIONS("SellersInstructions"),
    @XmlEnumValue("ShipperAssigned")
    SHIPPER_ASSIGNED("ShipperAssigned"),
    @XmlEnumValue("Shipper-AssignedCaseNumber")
    SHIPPER_ASSIGNED_CASE_NUMBER("Shipper-AssignedCaseNumber"),
    @XmlEnumValue("ShipperAssignedRollNumber")
    SHIPPER_ASSIGNED_ROLL_NUMBER("ShipperAssignedRollNumber"),
    @XmlEnumValue("ShipperAssignedSkidNumber")
    SHIPPER_ASSIGNED_SKID_NUMBER("ShipperAssignedSkidNumber"),
    @XmlEnumValue("SSCC-18")
    SSCC_18("SSCC-18"),
    @XmlEnumValue("SSCC-18AndApplicationIdentifier")
    SSCC_18_AND_APPLICATION_IDENTIFIER("SSCC-18AndApplicationIdentifier"),
    @XmlEnumValue("UPCShippingContainerCode")
    UPC_SHIPPING_CONTAINER_CODE("UPCShippingContainerCode"),
    @XmlEnumValue("UCCOrEAN128ApplicationIdentifierAndData")
    UCC_OR_EAN_128_APPLICATION_IDENTIFIER_AND_DATA("UCCOrEAN128ApplicationIdentifierAndData"),
    @XmlEnumValue("UniformCodeCouncilFormat")
    UNIFORM_CODE_COUNCIL_FORMAT("UniformCodeCouncilFormat"),
    @XmlEnumValue("UPCConsumerPackageCode-1-5-5-1")
    UPC_CONSUMER_PACKAGE_CODE_1_5_5_1("UPCConsumerPackageCode-1-5-5-1");
    private final String value;

    PackageMarkCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PackageMarkCode fromValue(String v) {
        for (PackageMarkCode c: PackageMarkCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
