//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartNumbers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartNumbers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerPartNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartNum"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BuyerPartNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartNum"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ManufacturerPartNumber" minOccurs="0"/>
 *         &lt;element name="StandardPartNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ProductIdentifierCoded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubstitutePartNumbers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfProductIdentifierCoded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OtherItemIdentifiers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfProductIdentifierCoded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartNumbers", propOrder = {
    "sellerPartNumber",
    "buyerPartNumber",
    "manufacturerPartNumber",
    "standardPartNumber",
    "substitutePartNumbers",
    "otherItemIdentifiers"
})
public class PartNumbers {

    @XmlElement(name = "SellerPartNumber")
    protected PartNumbers.SellerPartNumber sellerPartNumber;
    @XmlElement(name = "BuyerPartNumber")
    protected PartNumbers.BuyerPartNumber buyerPartNumber;
    @XmlElement(name = "ManufacturerPartNumber")
    protected ManufacturerPartNumber manufacturerPartNumber;
    @XmlElement(name = "StandardPartNumber")
    protected PartNumbers.StandardPartNumber standardPartNumber;
    @XmlElement(name = "SubstitutePartNumbers")
    protected PartNumbers.SubstitutePartNumbers substitutePartNumbers;
    @XmlElement(name = "OtherItemIdentifiers")
    protected PartNumbers.OtherItemIdentifiers otherItemIdentifiers;

    /**
     * Gets the value of the sellerPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumbers.SellerPartNumber }
     *     
     */
    public PartNumbers.SellerPartNumber getSellerPartNumber() {
        return sellerPartNumber;
    }

    /**
     * Sets the value of the sellerPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumbers.SellerPartNumber }
     *     
     */
    public void setSellerPartNumber(PartNumbers.SellerPartNumber value) {
        this.sellerPartNumber = value;
    }

    /**
     * Gets the value of the buyerPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumbers.BuyerPartNumber }
     *     
     */
    public PartNumbers.BuyerPartNumber getBuyerPartNumber() {
        return buyerPartNumber;
    }

    /**
     * Sets the value of the buyerPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumbers.BuyerPartNumber }
     *     
     */
    public void setBuyerPartNumber(PartNumbers.BuyerPartNumber value) {
        this.buyerPartNumber = value;
    }

    /**
     * Gets the value of the manufacturerPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerPartNumber }
     *     
     */
    public ManufacturerPartNumber getManufacturerPartNumber() {
        return manufacturerPartNumber;
    }

    /**
     * Sets the value of the manufacturerPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerPartNumber }
     *     
     */
    public void setManufacturerPartNumber(ManufacturerPartNumber value) {
        this.manufacturerPartNumber = value;
    }

    /**
     * Gets the value of the standardPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumbers.StandardPartNumber }
     *     
     */
    public PartNumbers.StandardPartNumber getStandardPartNumber() {
        return standardPartNumber;
    }

    /**
     * Sets the value of the standardPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumbers.StandardPartNumber }
     *     
     */
    public void setStandardPartNumber(PartNumbers.StandardPartNumber value) {
        this.standardPartNumber = value;
    }

    /**
     * Gets the value of the substitutePartNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumbers.SubstitutePartNumbers }
     *     
     */
    public PartNumbers.SubstitutePartNumbers getSubstitutePartNumbers() {
        return substitutePartNumbers;
    }

    /**
     * Sets the value of the substitutePartNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumbers.SubstitutePartNumbers }
     *     
     */
    public void setSubstitutePartNumbers(PartNumbers.SubstitutePartNumbers value) {
        this.substitutePartNumbers = value;
    }

    /**
     * Gets the value of the otherItemIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumbers.OtherItemIdentifiers }
     *     
     */
    public PartNumbers.OtherItemIdentifiers getOtherItemIdentifiers() {
        return otherItemIdentifiers;
    }

    /**
     * Sets the value of the otherItemIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumbers.OtherItemIdentifiers }
     *     
     */
    public void setOtherItemIdentifiers(PartNumbers.OtherItemIdentifiers value) {
        this.otherItemIdentifiers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartNum"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partNum"
    })
    public static class BuyerPartNumber {

        @XmlElement(name = "PartNum", required = true)
        protected PartNum partNum;

        /**
         * Gets the value of the partNum property.
         * 
         * @return
         *     possible object is
         *     {@link PartNum }
         *     
         */
        public PartNum getPartNum() {
            return partNum;
        }

        /**
         * Sets the value of the partNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartNum }
         *     
         */
        public void setPartNum(PartNum value) {
            this.partNum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfProductIdentifierCoded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listOfProductIdentifierCoded"
    })
    public static class OtherItemIdentifiers {

        @XmlElement(name = "ListOfProductIdentifierCoded", required = true)
        protected ListOfProductIdentifierCoded listOfProductIdentifierCoded;

        /**
         * Gets the value of the listOfProductIdentifierCoded property.
         * 
         * @return
         *     possible object is
         *     {@link ListOfProductIdentifierCoded }
         *     
         */
        public ListOfProductIdentifierCoded getListOfProductIdentifierCoded() {
            return listOfProductIdentifierCoded;
        }

        /**
         * Sets the value of the listOfProductIdentifierCoded property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListOfProductIdentifierCoded }
         *     
         */
        public void setListOfProductIdentifierCoded(ListOfProductIdentifierCoded value) {
            this.listOfProductIdentifierCoded = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}PartNum"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partNum"
    })
    public static class SellerPartNumber {

        @XmlElement(name = "PartNum", required = true)
        protected PartNum partNum;

        /**
         * Gets the value of the partNum property.
         * 
         * @return
         *     possible object is
         *     {@link PartNum }
         *     
         */
        public PartNum getPartNum() {
            return partNum;
        }

        /**
         * Sets the value of the partNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartNum }
         *     
         */
        public void setPartNum(PartNum value) {
            this.partNum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ProductIdentifierCoded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productIdentifierCoded"
    })
    public static class StandardPartNumber {

        @XmlElement(name = "ProductIdentifierCoded", required = true)
        protected ProductIdentifierCoded productIdentifierCoded;

        /**
         * Gets the value of the productIdentifierCoded property.
         * 
         * @return
         *     possible object is
         *     {@link ProductIdentifierCoded }
         *     
         */
        public ProductIdentifierCoded getProductIdentifierCoded() {
            return productIdentifierCoded;
        }

        /**
         * Sets the value of the productIdentifierCoded property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductIdentifierCoded }
         *     
         */
        public void setProductIdentifierCoded(ProductIdentifierCoded value) {
            this.productIdentifierCoded = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}ListOfProductIdentifierCoded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listOfProductIdentifierCoded"
    })
    public static class SubstitutePartNumbers {

        @XmlElement(name = "ListOfProductIdentifierCoded", required = true)
        protected ListOfProductIdentifierCoded listOfProductIdentifierCoded;

        /**
         * Gets the value of the listOfProductIdentifierCoded property.
         * 
         * @return
         *     possible object is
         *     {@link ListOfProductIdentifierCoded }
         *     
         */
        public ListOfProductIdentifierCoded getListOfProductIdentifierCoded() {
            return listOfProductIdentifierCoded;
        }

        /**
         * Sets the value of the listOfProductIdentifierCoded property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListOfProductIdentifierCoded }
         *     
         */
        public void setListOfProductIdentifierCoded(ListOfProductIdentifierCoded value) {
            this.listOfProductIdentifierCoded = value;
        }

    }

}
