//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnLoadCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReturnLoadCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="LoadedEithEmpty4BlockForBlockingPurposes"/>
 *     &lt;enumeration value="EmptyContainerWithDunnage"/>
 *     &lt;enumeration value="EmptyContainer"/>
 *     &lt;enumeration value="LoadedWithProductionMaterial"/>
 *     &lt;enumeration value="MixedEmptyAndLoaded"/>
 *     &lt;enumeration value="ObsoleteMaterial"/>
 *     &lt;enumeration value="LoadedWithExcessReturnedProductionMaterial"/>
 *     &lt;enumeration value="LoadedWithRejectedMaterial"/>
 *     &lt;enumeration value="ServicePartObsoleteContainer"/>
 *     &lt;enumeration value="LoadedWithReturnedProcessedMaterial"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReturnLoadCode")
@XmlEnum
public enum ReturnLoadCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("LoadedEithEmpty4BlockForBlockingPurposes")
    LOADED_EITH_EMPTY_4_BLOCK_FOR_BLOCKING_PURPOSES("LoadedEithEmpty4BlockForBlockingPurposes"),
    @XmlEnumValue("EmptyContainerWithDunnage")
    EMPTY_CONTAINER_WITH_DUNNAGE("EmptyContainerWithDunnage"),
    @XmlEnumValue("EmptyContainer")
    EMPTY_CONTAINER("EmptyContainer"),
    @XmlEnumValue("LoadedWithProductionMaterial")
    LOADED_WITH_PRODUCTION_MATERIAL("LoadedWithProductionMaterial"),
    @XmlEnumValue("MixedEmptyAndLoaded")
    MIXED_EMPTY_AND_LOADED("MixedEmptyAndLoaded"),
    @XmlEnumValue("ObsoleteMaterial")
    OBSOLETE_MATERIAL("ObsoleteMaterial"),
    @XmlEnumValue("LoadedWithExcessReturnedProductionMaterial")
    LOADED_WITH_EXCESS_RETURNED_PRODUCTION_MATERIAL("LoadedWithExcessReturnedProductionMaterial"),
    @XmlEnumValue("LoadedWithRejectedMaterial")
    LOADED_WITH_REJECTED_MATERIAL("LoadedWithRejectedMaterial"),
    @XmlEnumValue("ServicePartObsoleteContainer")
    SERVICE_PART_OBSOLETE_CONTAINER("ServicePartObsoleteContainer"),
    @XmlEnumValue("LoadedWithReturnedProcessedMaterial")
    LOADED_WITH_RETURNED_PROCESSED_MATERIAL("LoadedWithReturnedProcessedMaterial");
    private final String value;

    ReturnLoadCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReturnLoadCode fromValue(String v) {
        for (ReturnLoadCode c: ReturnLoadCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
