//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoundTripInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoundTripInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Immutable" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}xcblBoolean" minOccurs="0"/>
 *         &lt;element name="ReLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="SupplierShoppingCartID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RoundTripOrder" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}xcblBoolean" fixed="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoundTripInformation", propOrder = {
    "immutable",
    "reLink",
    "supplierShoppingCartID"
})
public class RoundTripInformation {

    @XmlElement(name = "Immutable")
    protected Boolean immutable;
    @XmlElement(name = "ReLink")
    @XmlSchemaType(name = "anyURI")
    protected String reLink;
    @XmlElement(name = "SupplierShoppingCartID")
    protected String supplierShoppingCartID;
    @XmlAttribute(name = "RoundTripOrder")
    protected Boolean roundTripOrder;

    /**
     * Gets the value of the immutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImmutable() {
        return immutable;
    }

    /**
     * Sets the value of the immutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImmutable(Boolean value) {
        this.immutable = value;
    }

    /**
     * Gets the value of the reLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReLink() {
        return reLink;
    }

    /**
     * Sets the value of the reLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReLink(String value) {
        this.reLink = value;
    }

    /**
     * Gets the value of the supplierShoppingCartID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierShoppingCartID() {
        return supplierShoppingCartID;
    }

    /**
     * Sets the value of the supplierShoppingCartID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierShoppingCartID(String value) {
        this.supplierShoppingCartID = value;
    }

    /**
     * Gets the value of the roundTripOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRoundTripOrder() {
        if (roundTripOrder == null) {
            return true;
        } else {
            return roundTripOrder;
        }
    }

    /**
     * Sets the value of the roundTripOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRoundTripOrder(Boolean value) {
        this.roundTripOrder = value;
    }

}
