//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesRequirementCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SalesRequirementCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="AddQuantityToMakeMinimumWeightRequirement"/>
 *     &lt;enumeration value="BackOrderIfItemsAreOutOfStockOrNotYetPublished"/>
 *     &lt;enumeration value="BackOrderIfOutOfStock"/>
 *     &lt;enumeration value="BackOrderOnlyIfNewItem"/>
 *     &lt;enumeration value="BidGuarantee"/>
 *     &lt;enumeration value="CombinedSmallDisadvantagedBusinessAndLaborSurplusAreaSet-Aside"/>
 *     &lt;enumeration value="Consignment"/>
 *     &lt;enumeration value="DoNotPreship"/>
 *     &lt;enumeration value="EqualProductAllowed"/>
 *     &lt;enumeration value="ExcludeImportQuotaInFirstCost"/>
 *     &lt;enumeration value="FactoryShip"/>
 *     &lt;enumeration value="GuaranteedSale"/>
 *     &lt;enumeration value="IncludeImportQuotaInFirstCost"/>
 *     &lt;enumeration value="LaborSurplusAreaSet-Aside"/>
 *     &lt;enumeration value="LargePurchaseSet-AsideForSmallBusiness"/>
 *     &lt;enumeration value="MayPreship"/>
 *     &lt;enumeration value="Multi-yearAward"/>
 *     &lt;enumeration value="NoBackOrder"/>
 *     &lt;enumeration value="NoSubstitutes"/>
 *     &lt;enumeration value="NotifyPriorToShipmentIfQuantitySpecifiedIsNotAvailable"/>
 *     &lt;enumeration value="OnQualifiedBiddersList"/>
 *     &lt;enumeration value="OnQualifiedManufacturersList"/>
 *     &lt;enumeration value="OtherUnlistedSalesCondition"/>
 *     &lt;enumeration value="PartialLaborSurplusAreaSetAside"/>
 *     &lt;enumeration value="RestrictedToApprovedSources"/>
 *     &lt;enumeration value="RestrictedToEducationalInstitutions"/>
 *     &lt;enumeration value="RestrictedToHistoricallyBlackCollegeOrUniversityOrMinorityInstitution"/>
 *     &lt;enumeration value="RestrictedToIndustrialPreparednessProgramParticipants"/>
 *     &lt;enumeration value="RestrictedToQualifiedProductsListProducts"/>
 *     &lt;enumeration value="RestrictedToUSAndCanadianSources"/>
 *     &lt;enumeration value="RestrictedToYoungInvestigatorProgram"/>
 *     &lt;enumeration value="Section8aSet-Aside"/>
 *     &lt;enumeration value="Set-asideForAmericanIndian-ownedBusiness"/>
 *     &lt;enumeration value="ShipAsSoonAsPossible"/>
 *     &lt;enumeration value="ShipComplete"/>
 *     &lt;enumeration value="ShipFullTruckOnly"/>
 *     &lt;enumeration value="ShipIn-Place"/>
 *     &lt;enumeration value="ShipPartial-BalanceBackOrder"/>
 *     &lt;enumeration value="ShipPartialBalanceCancel"/>
 *     &lt;enumeration value="ShipPartialBalanceSubstitute"/>
 *     &lt;enumeration value="ShipPartialCarloadLotsOnly"/>
 *     &lt;enumeration value="ShipPartialItemQtyProportionalToTotalOrder"/>
 *     &lt;enumeration value="ShipPartialTruckloadLotsOnly"/>
 *     &lt;enumeration value="ShipPerRelease"/>
 *     &lt;enumeration value="ShipPerReleaseorBuyerAuthorization"/>
 *     &lt;enumeration value="ShipPerSchedule"/>
 *     &lt;enumeration value="SmallBusinessWithSmallDisadvantagedBusinessConsiderationSet-Aside"/>
 *     &lt;enumeration value="SmallDisadvantagedBusinessSet-Aside"/>
 *     &lt;enumeration value="SmallPurchaseSetAsideForSmallBusinesses"/>
 *     &lt;enumeration value="SmallRemainingBalanceCancellationAllowed"/>
 *     &lt;enumeration value="SmallRemainingBalanceCancellationNotAllowed"/>
 *     &lt;enumeration value="SubstituteItemAllowed"/>
 *     &lt;enumeration value="UnrestrictedProcurement"/>
 *     &lt;enumeration value="WarehouseShip"/>
 *     &lt;enumeration value="Warranty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SalesRequirementCode")
@XmlEnum
public enum SalesRequirementCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("AddQuantityToMakeMinimumWeightRequirement")
    ADD_QUANTITY_TO_MAKE_MINIMUM_WEIGHT_REQUIREMENT("AddQuantityToMakeMinimumWeightRequirement"),
    @XmlEnumValue("BackOrderIfItemsAreOutOfStockOrNotYetPublished")
    BACK_ORDER_IF_ITEMS_ARE_OUT_OF_STOCK_OR_NOT_YET_PUBLISHED("BackOrderIfItemsAreOutOfStockOrNotYetPublished"),
    @XmlEnumValue("BackOrderIfOutOfStock")
    BACK_ORDER_IF_OUT_OF_STOCK("BackOrderIfOutOfStock"),
    @XmlEnumValue("BackOrderOnlyIfNewItem")
    BACK_ORDER_ONLY_IF_NEW_ITEM("BackOrderOnlyIfNewItem"),
    @XmlEnumValue("BidGuarantee")
    BID_GUARANTEE("BidGuarantee"),
    @XmlEnumValue("CombinedSmallDisadvantagedBusinessAndLaborSurplusAreaSet-Aside")
    COMBINED_SMALL_DISADVANTAGED_BUSINESS_AND_LABOR_SURPLUS_AREA_SET_ASIDE("CombinedSmallDisadvantagedBusinessAndLaborSurplusAreaSet-Aside"),
    @XmlEnumValue("Consignment")
    CONSIGNMENT("Consignment"),
    @XmlEnumValue("DoNotPreship")
    DO_NOT_PRESHIP("DoNotPreship"),
    @XmlEnumValue("EqualProductAllowed")
    EQUAL_PRODUCT_ALLOWED("EqualProductAllowed"),
    @XmlEnumValue("ExcludeImportQuotaInFirstCost")
    EXCLUDE_IMPORT_QUOTA_IN_FIRST_COST("ExcludeImportQuotaInFirstCost"),
    @XmlEnumValue("FactoryShip")
    FACTORY_SHIP("FactoryShip"),
    @XmlEnumValue("GuaranteedSale")
    GUARANTEED_SALE("GuaranteedSale"),
    @XmlEnumValue("IncludeImportQuotaInFirstCost")
    INCLUDE_IMPORT_QUOTA_IN_FIRST_COST("IncludeImportQuotaInFirstCost"),
    @XmlEnumValue("LaborSurplusAreaSet-Aside")
    LABOR_SURPLUS_AREA_SET_ASIDE("LaborSurplusAreaSet-Aside"),
    @XmlEnumValue("LargePurchaseSet-AsideForSmallBusiness")
    LARGE_PURCHASE_SET_ASIDE_FOR_SMALL_BUSINESS("LargePurchaseSet-AsideForSmallBusiness"),
    @XmlEnumValue("MayPreship")
    MAY_PRESHIP("MayPreship"),
    @XmlEnumValue("Multi-yearAward")
    MULTI_YEAR_AWARD("Multi-yearAward"),
    @XmlEnumValue("NoBackOrder")
    NO_BACK_ORDER("NoBackOrder"),
    @XmlEnumValue("NoSubstitutes")
    NO_SUBSTITUTES("NoSubstitutes"),
    @XmlEnumValue("NotifyPriorToShipmentIfQuantitySpecifiedIsNotAvailable")
    NOTIFY_PRIOR_TO_SHIPMENT_IF_QUANTITY_SPECIFIED_IS_NOT_AVAILABLE("NotifyPriorToShipmentIfQuantitySpecifiedIsNotAvailable"),
    @XmlEnumValue("OnQualifiedBiddersList")
    ON_QUALIFIED_BIDDERS_LIST("OnQualifiedBiddersList"),
    @XmlEnumValue("OnQualifiedManufacturersList")
    ON_QUALIFIED_MANUFACTURERS_LIST("OnQualifiedManufacturersList"),
    @XmlEnumValue("OtherUnlistedSalesCondition")
    OTHER_UNLISTED_SALES_CONDITION("OtherUnlistedSalesCondition"),
    @XmlEnumValue("PartialLaborSurplusAreaSetAside")
    PARTIAL_LABOR_SURPLUS_AREA_SET_ASIDE("PartialLaborSurplusAreaSetAside"),
    @XmlEnumValue("RestrictedToApprovedSources")
    RESTRICTED_TO_APPROVED_SOURCES("RestrictedToApprovedSources"),
    @XmlEnumValue("RestrictedToEducationalInstitutions")
    RESTRICTED_TO_EDUCATIONAL_INSTITUTIONS("RestrictedToEducationalInstitutions"),
    @XmlEnumValue("RestrictedToHistoricallyBlackCollegeOrUniversityOrMinorityInstitution")
    RESTRICTED_TO_HISTORICALLY_BLACK_COLLEGE_OR_UNIVERSITY_OR_MINORITY_INSTITUTION("RestrictedToHistoricallyBlackCollegeOrUniversityOrMinorityInstitution"),
    @XmlEnumValue("RestrictedToIndustrialPreparednessProgramParticipants")
    RESTRICTED_TO_INDUSTRIAL_PREPAREDNESS_PROGRAM_PARTICIPANTS("RestrictedToIndustrialPreparednessProgramParticipants"),
    @XmlEnumValue("RestrictedToQualifiedProductsListProducts")
    RESTRICTED_TO_QUALIFIED_PRODUCTS_LIST_PRODUCTS("RestrictedToQualifiedProductsListProducts"),
    @XmlEnumValue("RestrictedToUSAndCanadianSources")
    RESTRICTED_TO_US_AND_CANADIAN_SOURCES("RestrictedToUSAndCanadianSources"),
    @XmlEnumValue("RestrictedToYoungInvestigatorProgram")
    RESTRICTED_TO_YOUNG_INVESTIGATOR_PROGRAM("RestrictedToYoungInvestigatorProgram"),
    @XmlEnumValue("Section8aSet-Aside")
    SECTION_8_A_SET_ASIDE("Section8aSet-Aside"),
    @XmlEnumValue("Set-asideForAmericanIndian-ownedBusiness")
    SET_ASIDE_FOR_AMERICAN_INDIAN_OWNED_BUSINESS("Set-asideForAmericanIndian-ownedBusiness"),
    @XmlEnumValue("ShipAsSoonAsPossible")
    SHIP_AS_SOON_AS_POSSIBLE("ShipAsSoonAsPossible"),
    @XmlEnumValue("ShipComplete")
    SHIP_COMPLETE("ShipComplete"),
    @XmlEnumValue("ShipFullTruckOnly")
    SHIP_FULL_TRUCK_ONLY("ShipFullTruckOnly"),
    @XmlEnumValue("ShipIn-Place")
    SHIP_IN_PLACE("ShipIn-Place"),
    @XmlEnumValue("ShipPartial-BalanceBackOrder")
    SHIP_PARTIAL_BALANCE_BACK_ORDER("ShipPartial-BalanceBackOrder"),
    @XmlEnumValue("ShipPartialBalanceCancel")
    SHIP_PARTIAL_BALANCE_CANCEL("ShipPartialBalanceCancel"),
    @XmlEnumValue("ShipPartialBalanceSubstitute")
    SHIP_PARTIAL_BALANCE_SUBSTITUTE("ShipPartialBalanceSubstitute"),
    @XmlEnumValue("ShipPartialCarloadLotsOnly")
    SHIP_PARTIAL_CARLOAD_LOTS_ONLY("ShipPartialCarloadLotsOnly"),
    @XmlEnumValue("ShipPartialItemQtyProportionalToTotalOrder")
    SHIP_PARTIAL_ITEM_QTY_PROPORTIONAL_TO_TOTAL_ORDER("ShipPartialItemQtyProportionalToTotalOrder"),
    @XmlEnumValue("ShipPartialTruckloadLotsOnly")
    SHIP_PARTIAL_TRUCKLOAD_LOTS_ONLY("ShipPartialTruckloadLotsOnly"),
    @XmlEnumValue("ShipPerRelease")
    SHIP_PER_RELEASE("ShipPerRelease"),
    @XmlEnumValue("ShipPerReleaseorBuyerAuthorization")
    SHIP_PER_RELEASEOR_BUYER_AUTHORIZATION("ShipPerReleaseorBuyerAuthorization"),
    @XmlEnumValue("ShipPerSchedule")
    SHIP_PER_SCHEDULE("ShipPerSchedule"),
    @XmlEnumValue("SmallBusinessWithSmallDisadvantagedBusinessConsiderationSet-Aside")
    SMALL_BUSINESS_WITH_SMALL_DISADVANTAGED_BUSINESS_CONSIDERATION_SET_ASIDE("SmallBusinessWithSmallDisadvantagedBusinessConsiderationSet-Aside"),
    @XmlEnumValue("SmallDisadvantagedBusinessSet-Aside")
    SMALL_DISADVANTAGED_BUSINESS_SET_ASIDE("SmallDisadvantagedBusinessSet-Aside"),
    @XmlEnumValue("SmallPurchaseSetAsideForSmallBusinesses")
    SMALL_PURCHASE_SET_ASIDE_FOR_SMALL_BUSINESSES("SmallPurchaseSetAsideForSmallBusinesses"),
    @XmlEnumValue("SmallRemainingBalanceCancellationAllowed")
    SMALL_REMAINING_BALANCE_CANCELLATION_ALLOWED("SmallRemainingBalanceCancellationAllowed"),
    @XmlEnumValue("SmallRemainingBalanceCancellationNotAllowed")
    SMALL_REMAINING_BALANCE_CANCELLATION_NOT_ALLOWED("SmallRemainingBalanceCancellationNotAllowed"),
    @XmlEnumValue("SubstituteItemAllowed")
    SUBSTITUTE_ITEM_ALLOWED("SubstituteItemAllowed"),
    @XmlEnumValue("UnrestrictedProcurement")
    UNRESTRICTED_PROCUREMENT("UnrestrictedProcurement"),
    @XmlEnumValue("WarehouseShip")
    WAREHOUSE_SHIP("WarehouseShip"),
    @XmlEnumValue("Warranty")
    WARRANTY("Warranty");
    private final String value;

    SalesRequirementCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SalesRequirementCode fromValue(String v) {
        for (SalesRequirementCode c: SalesRequirementCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
