//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SealInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SealInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SealNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}SealIssuer" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}SealStatusDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SealInfo", propOrder = {
    "sealNumber",
    "sealIssuer",
    "sealStatusDescription"
})
public class SealInfo {

    @XmlElement(name = "SealNumber", required = true)
    protected String sealNumber;
    @XmlElement(name = "SealIssuer")
    protected SealIssuer sealIssuer;
    @XmlElement(name = "SealStatusDescription")
    protected SealStatusDescription sealStatusDescription;

    /**
     * Gets the value of the sealNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber() {
        return sealNumber;
    }

    /**
     * Sets the value of the sealNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber(String value) {
        this.sealNumber = value;
    }

    /**
     * Gets the value of the sealIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link SealIssuer }
     *     
     */
    public SealIssuer getSealIssuer() {
        return sealIssuer;
    }

    /**
     * Sets the value of the sealIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SealIssuer }
     *     
     */
    public void setSealIssuer(SealIssuer value) {
        this.sealIssuer = value;
    }

    /**
     * Gets the value of the sealStatusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link SealStatusDescription }
     *     
     */
    public SealStatusDescription getSealStatusDescription() {
        return sealStatusDescription;
    }

    /**
     * Sets the value of the sealStatusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SealStatusDescription }
     *     
     */
    public void setSealStatusDescription(SealStatusDescription value) {
        this.sealStatusDescription = value;
    }

}
