//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SealStatusCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SealStatusCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Broken"/>
 *     &lt;enumeration value="Damaged"/>
 *     &lt;enumeration value="InRightCondition"/>
 *     &lt;enumeration value="Missing"/>
 *     &lt;enumeration value="Replaced"/>
 *     &lt;enumeration value="TheElectronicSealIsFaulty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SealStatusCode")
@XmlEnum
public enum SealStatusCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Broken")
    BROKEN("Broken"),
    @XmlEnumValue("Damaged")
    DAMAGED("Damaged"),
    @XmlEnumValue("InRightCondition")
    IN_RIGHT_CONDITION("InRightCondition"),
    @XmlEnumValue("Missing")
    MISSING("Missing"),
    @XmlEnumValue("Replaced")
    REPLACED("Replaced"),
    @XmlEnumValue("TheElectronicSealIsFaulty")
    THE_ELECTRONIC_SEAL_IS_FAULTY("TheElectronicSealIsFaulty");
    private final String value;

    SealStatusCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SealStatusCode fromValue(String v) {
        for (SealStatusCode c: SealStatusCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
