//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructuredNote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructuredNote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeneralNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NoteID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}Agency" minOccurs="0"/>
 *         &lt;element name="NoteURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="TextTypeCoded" type="{rrn:org.xcbl:schemas/xcbl/v3_5/xcbl35.xsd}TextTypeCode" minOccurs="0"/>
 *         &lt;element name="TextTypeCodedOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructuredNote", propOrder = {
    "generalNote",
    "noteID",
    "agency",
    "noteURL",
    "textTypeCoded",
    "textTypeCodedOther"
})
public class StructuredNote {

    @XmlElement(name = "GeneralNote")
    protected String generalNote;
    @XmlElement(name = "NoteID")
    protected String noteID;
    @XmlElement(name = "Agency")
    protected Agency agency;
    @XmlElement(name = "NoteURL")
    @XmlSchemaType(name = "anyURI")
    protected String noteURL;
    @XmlElement(name = "TextTypeCoded")
    protected TextTypeCode textTypeCoded;
    @XmlElement(name = "TextTypeCodedOther")
    protected String textTypeCodedOther;

    /**
     * Gets the value of the generalNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralNote() {
        return generalNote;
    }

    /**
     * Sets the value of the generalNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralNote(String value) {
        this.generalNote = value;
    }

    /**
     * Gets the value of the noteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteID() {
        return noteID;
    }

    /**
     * Sets the value of the noteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteID(String value) {
        this.noteID = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link Agency }
     *     
     */
    public Agency getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agency }
     *     
     */
    public void setAgency(Agency value) {
        this.agency = value;
    }

    /**
     * Gets the value of the noteURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteURL() {
        return noteURL;
    }

    /**
     * Sets the value of the noteURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteURL(String value) {
        this.noteURL = value;
    }

    /**
     * Gets the value of the textTypeCoded property.
     * 
     * @return
     *     possible object is
     *     {@link TextTypeCode }
     *     
     */
    public TextTypeCode getTextTypeCoded() {
        return textTypeCoded;
    }

    /**
     * Sets the value of the textTypeCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextTypeCode }
     *     
     */
    public void setTextTypeCoded(TextTypeCode value) {
        this.textTypeCoded = value;
    }

    /**
     * Gets the value of the textTypeCodedOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextTypeCodedOther() {
        return textTypeCodedOther;
    }

    /**
     * Sets the value of the textTypeCodedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextTypeCodedOther(String value) {
        this.textTypeCodedOther = value;
    }

}
