//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermsOfDeliveryFunctionCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TermsOfDeliveryFunctionCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="PriceCondition"/>
 *     &lt;enumeration value="DespatchCondition"/>
 *     &lt;enumeration value="PriceandDespatchCondition"/>
 *     &lt;enumeration value="CollectedByCustomer"/>
 *     &lt;enumeration value="TransportCondition"/>
 *     &lt;enumeration value="DeliveryCondition"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TermsOfDeliveryFunctionCode")
@XmlEnum
public enum TermsOfDeliveryFunctionCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("PriceCondition")
    PRICE_CONDITION("PriceCondition"),
    @XmlEnumValue("DespatchCondition")
    DESPATCH_CONDITION("DespatchCondition"),
    @XmlEnumValue("PriceandDespatchCondition")
    PRICEAND_DESPATCH_CONDITION("PriceandDespatchCondition"),
    @XmlEnumValue("CollectedByCustomer")
    COLLECTED_BY_CUSTOMER("CollectedByCustomer"),
    @XmlEnumValue("TransportCondition")
    TRANSPORT_CONDITION("TransportCondition"),
    @XmlEnumValue("DeliveryCondition")
    DELIVERY_CONDITION("DeliveryCondition");
    private final String value;

    TermsOfDeliveryFunctionCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TermsOfDeliveryFunctionCode fromValue(String v) {
        for (TermsOfDeliveryFunctionCode c: TermsOfDeliveryFunctionCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
