//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 03:22:36 PM IST 
//


package rrn.org_xcbl.schemas.xcbl.v3_5.xcbl35;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransportTermsCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransportTermsCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Ex-Works"/>
 *     &lt;enumeration value="Free-Carrier"/>
 *     &lt;enumeration value="FreeAlongsideShip"/>
 *     &lt;enumeration value="FreeOnBoard"/>
 *     &lt;enumeration value="CostAndFreight"/>
 *     &lt;enumeration value="Cost-InsuranceAndFreight"/>
 *     &lt;enumeration value="CarriagePaidTo"/>
 *     &lt;enumeration value="Carriage-InsurancePaidTo"/>
 *     &lt;enumeration value="DeliveredAtFrontier"/>
 *     &lt;enumeration value="DeliveredEx-Ship"/>
 *     &lt;enumeration value="DeliveredEx-Quay"/>
 *     &lt;enumeration value="DeliveredDutyUnpaid"/>
 *     &lt;enumeration value="DeliveredDutyPaid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransportTermsCode")
@XmlEnum
public enum TransportTermsCode {

    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Ex-Works")
    EX_WORKS("Ex-Works"),
    @XmlEnumValue("Free-Carrier")
    FREE_CARRIER("Free-Carrier"),
    @XmlEnumValue("FreeAlongsideShip")
    FREE_ALONGSIDE_SHIP("FreeAlongsideShip"),
    @XmlEnumValue("FreeOnBoard")
    FREE_ON_BOARD("FreeOnBoard"),
    @XmlEnumValue("CostAndFreight")
    COST_AND_FREIGHT("CostAndFreight"),
    @XmlEnumValue("Cost-InsuranceAndFreight")
    COST_INSURANCE_AND_FREIGHT("Cost-InsuranceAndFreight"),
    @XmlEnumValue("CarriagePaidTo")
    CARRIAGE_PAID_TO("CarriagePaidTo"),
    @XmlEnumValue("Carriage-InsurancePaidTo")
    CARRIAGE_INSURANCE_PAID_TO("Carriage-InsurancePaidTo"),
    @XmlEnumValue("DeliveredAtFrontier")
    DELIVERED_AT_FRONTIER("DeliveredAtFrontier"),
    @XmlEnumValue("DeliveredEx-Ship")
    DELIVERED_EX_SHIP("DeliveredEx-Ship"),
    @XmlEnumValue("DeliveredEx-Quay")
    DELIVERED_EX_QUAY("DeliveredEx-Quay"),
    @XmlEnumValue("DeliveredDutyUnpaid")
    DELIVERED_DUTY_UNPAID("DeliveredDutyUnpaid"),
    @XmlEnumValue("DeliveredDutyPaid")
    DELIVERED_DUTY_PAID("DeliveredDutyPaid");
    private final String value;

    TransportTermsCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransportTermsCode fromValue(String v) {
        for (TransportTermsCode c: TransportTermsCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
