apiVersion: v1
kind: Service
metadata:
  name: transactiondataservice
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: http
  - port: 8087
    targetPort: 8087
    name: management
  selector:
    app: transactiondataservice
  type: LoadBalancer