apiVersion: v1
kind: Service
metadata:
  name: receivexcblorder
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  - port: 8083
    targetPort: 8083
    name: management
  selector:
    app: receivexcblorder
  type: LoadBalancer